language: node_js
deploy:
  api_key:
    secure: Ca3wgEpZYdeDj24L8ZnwcEyC3JMc4GDYM5o5Um8UbJXH1HMON9P39PEh9EHJ9p8mZpXxy6sMaN4FzeJVKAAtKnXYwdnpT4YyexNldLBoG/Kt5NJALWiU0NCuxJZquXAMZzt+8AOzn8PsJl1t4i5RdUvenKOdmQVHKJJbgvymaNQ=
  provider: npm
  email: john@mclear.co.uk
